turn arguments to options(switches)
MortezaBashsiz/CFScanner pull request #181
Opened 2023-03-04 11:47 UTC by mahdibahramih

I turn passed bash arguments to switch.
in this change I remove this part of the code :
subnetOrIP="$1" downloadOrUpload="$2" threads="$3" tryCount="$4" config="$5" speed="$6"
and replace it with a while loop that parses the passed switch to the command
also, I added a Help function for the cfScanner.sh script.
if you think this is helpful please merge it

2023-03-04 14:42 UTC, MortezaBashsiz requested changes

2023-03-04 14:42 UTC, MortezaBashsiz commented on bash/cfScanner.sh
> +		 [ -c|--config <configgile> ]
configfile

2023-03-04 14:42 UTC, MortezaBashsiz commented on bash/cfScanner.sh
> +		 [ -f|--custom-subnet-file <custome-ip-file> (if you chose IP mode)]\n"
--file instead of --custom-subnet-file

2023-03-04 14:42 UTC, MortezaBashsiz commented on bash/cfScanner.sh
> +PARSED_ARGUMENTS=$(getopt -a -n  cfScanner -o m:t:thr:try:c:s:f: --long mode:,test-type:,thread:,tryCount:,config:,speed:,custom-subnet-file: -- "$@")
variable name
parsedArguments

2023-03-04 14:42 UTC, MortezaBashsiz commented on bash/cfScanner.sh
> +VALID_ARGUMENTS=$?
variable name
validArguments

2023-03-04 15:40 UTC, mahdibahramih commented
I did changes
also, I changed README.md based on this MR

2023-03-05 09:28 UTC, MortezaBashsiz approved these changes

2023-03-05 09:29 UTC, merged