refactor(python code): Add a few minor changes
MortezaBashsiz/CFScanner pull request #232
Opened 2023-03-09 12:37 UTC by amirmalekian

2023-03-09 13:36 UTC, tempookian commented on python/clog.py
> +            if prefix := record.args.get("prefix"):
Let's keep compatibility with Python 3.6

2023-03-09 15:08 UTC, tempookian requested changes
Just a minor change to keep compatibility

2023-03-10 17:44 UTC, tempookian approved these changes

2023-03-10 17:45 UTC, tempookian commented
@MortezaBashsiz as far as Python is concerned, everything is fine and ready to be merged

2023-03-11 06:28 UTC, merged

2023-03-11 06:29 UTC, MortezaBashsiz commented
Merged
Thanks